#!/bin/bash

# batsh queuer

log() {
    printf "[%(%Y-%m-%d %H:%M:%S)T] %s\n" -1 "$@"
}

IFS=$'\n' 

readarray -t commands

log "read ${#commands[@]} commands:"
printf '%s\n' "${commands[@]}"

cmd_fifo=./var/batsh_cmd.fifo
rdy_fifo=./var/batsh_rdy.fifo

mkdir -p "$(dirname $cmd_fifo)" "$(dirname $rdy_fifo)"
[[ ! -p "$cmd_fifo" ]] && mkfifo "$cmd_fifo"
[[ ! -p "$rdy_fifo" ]] && mkfifo "$rdy_fifo"

nready=0
ncomplete=0
n=${n:-0}

for (( ; n == 0 || ncomplete < n; )); do
  log "$ncomplete done (n=$n, nready=$nready)"
  for (( ; 0 < nready; ncomplete++ )); do
    cmd="${commands[ncomplete % ${#commands[@]}]}"
    printf '%s\n' "$cmd" >>"$cmd_fifo" || exit
    (( nready-- ))
  done
  read -r rdy <"$rdy_fifo" || exit
  (( ++nready ))
done
