#!/bin/bash

# batsh queuer

log() {
    printf "[%(%Y-%m-%d %H:%M:%S)T] %s\n" -1 "$*"
}

oops() {
    printf "\x1b[31;1moops\x1b[0m: %s\n" "$*" >&2
    exit 1
}

IFS=$'\n' 

while getopts "n:" opt; do
  case "$opt" in
    n) n="$OPTARG";;
    ?) exit 1
  esac
done

[[ ! "$n" =~ ^[0-9]+$ ]] && oops "specify -n <maxjobs | 0>"

log "reading commands from stdin"
readarray -t commands

log "read ${#commands[@]} commands:"
printf '%s\n' "${commands[@]}"

cmd_fifo=./var/batsh_cmd.fifo
rdy_fifo=./var/batsh_rdy.fifo

mkdir -p "$(dirname $cmd_fifo)" "$(dirname $rdy_fifo)"
[[ ! -p "$cmd_fifo" ]] && mkfifo "$cmd_fifo"
[[ ! -p "$rdy_fifo" ]] && mkfifo "$rdy_fifo"

nready=0
ncomplete=0

for (( ; n == 0 || ncomplete < n; )); do
  log "$ncomplete done (n=$n, nready=$nready)"
  for (( ; 0 < nready; ncomplete++ )); do
    cmd="${commands[ncomplete % ${#commands[@]}]}"
    log "\$ $cmd"
    printf '%s\n' "$cmd" >>"$cmd_fifo" || exit
    (( nready-- ))
  done
  read -r rdy <"$rdy_fifo" || exit
  (( ++nready ))
done
