#!/bin/bash

python=${python:-./env/bin/python}
script=${script:-./src/__main__.py}
flags="GUI_HEADLESS=true"
rundir="EXPLORATION_RUNS_DIR=./var/runs_"

jobs=(
    # Compare PV in all five conditions
    "$flags ${rundir}ours       PARAME_PROFILE=[shortrange,pv"{0000,0050,0100,0200,0300,0500,0800,1200,1600,inf}",ours]          $python $script"
    "$flags ${rundir}gn         PARAME_PROFILE=[shortrange,pv"{0000,0050,0100,0200,0300,0500,0800,1200,1600,inf}",gn]            $python $script"
    "$flags ${rundir}bfs        PARAME_PROFILE=[shortrange,pv"{0000,0050,0100,0200,0300,0500,0800,1200,1600,inf}",bfs]           $python $script"
    "$flags ${rundir}tree       PARAME_PROFILE=[shortrange,pv"{0000,0050,0100,0200,0300,0500,0800,1200,1600,inf}",tree]          $python $script"
    "$flags ${rundir}uni        PARAME_PROFILE=[shortrange,pv"{0000,0050,0100,0200,0300,0500,0800,1200,1600,inf}",uniform]       $python $script"
    "$flags ${rundir}nj         PARAME_PROFILE=[shortrange,pv"{0000,0050,0100,0200,0300,0500,0800,1200,1600,inf}",nojump]        $python $script"

    # Not terribly interest in these GN experiments.
    #"$flags ${rundir}gn_bfs     PARAME_PROFILE=[shortrange,pv"{000,050,100,200,300,500,inf}",gn,bfs]        $python $script"
    #"$flags ${rundir}gn_uni     PARAME_PROFILE=[shortrange,pv"{000,050,100,200,300,500,inf}",gn,uniform]    $python $script"
    #"$flags ${rundir}gn_nj      PARAME_PROFILE=[shortrange,pv"{000,050,100,200,300,500,inf}",gn,nojump]     $python $script"

    # Compare tree-like pathing (without PV.)
    "$flags ${rundir}tree_uni       PARAME_PROFILE=[shortrange,pv0000,tree,uniform]      $python $script"
    "$flags ${rundir}tree_nj        PARAME_PROFILE=[shortrange,pv0000,tree,nojump]       $python $script"
    "$flags ${rundir}tree_gn        PARAME_PROFILE=[shortrange,pv0000,tree,gn]           $python $script"
    "$flags ${rundir}tree_uni_gn    PARAME_PROFILE=[shortrange,pv0000,tree,uniform,gn]   $python $script"

    #"$flags ${rundir}uni_nj     PARAME_PROFILE=[shortrange,pvinf,uniform,nojump] $python $script"
    #"$flags ${rundir}gn_bfs_nj  PARAME_PROFILE=[shortrange,pv"{000,050,100,200,300,500,inf}",gn,bfs,nojump]  $python $script"
    #"$flags ${rundir}gn_uni_nj  PARAME_PROFILE=[shortrange,pvinf,gn,uniform,nojump] $python $script"

)

printf "%s\n" "${jobs[@]}";
